---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: rhtap-integration-service-rpa
  namespace: rh-managed-rhtap-ser-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - integration-service
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    infra-deployment-update-script: |
      sed -i -e 's|\(https://github.com/redhat-appstudio/integration-service/.*?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/integration/development/kustomization.yaml
      sed -i -e 's|\(https://github.com/redhat-appstudio/integration-service/.*?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/integration/staging/base/kustomization.yaml
      # Temporary disabled grafana updates
      # sed -i -e 's|\(https://github.com/redhat-appstudio/integration-service/.*?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
    mapping:
      components:
        - name: integration-service
          repository: "quay.io/redhat-appstudio/integration-service"
    pyxis:
      secret: pyxis-production-secret
      server: production
  origin: rhtap-integration-tenant
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/redhat-appstudio/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/rhtap-service-push/rhtap-service-push.yaml"
    serviceAccountName: rhtap-servicerelease-sa
  policy: rh-policy
